# Generated by Django 5.2.9 on 2025-12-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ogrenci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ogrenci_no", models.CharField(max_length=10, unique=True)),
                ("ad_soyad", models.CharField(max_length=100)),
                ("yuz_kodlama", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="YoklamaKaydi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zaman", models.DateTimeField(auto_now_add=True)),
                (
                    "durum",
                    models.CharField(
                        choices=[("GIRIS", "Giriş"), ("CIKIS", "Çıkış")], max_length=10
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yoklamaapp.ogrenci",
                    ),
                ),
            ],
        ),
    ]
